routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect('/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => 'auth'], function($router) {
    // интерфейс управления автомобилями
    Route::resource('cars', 'CarController');
    // загрузка фото для автомобиля
    Route::post('/cars/{id}/uploadPhoto', 'CarController@uploadPhotos');
    // просмотр фото автомобиля
    Route::post('/cars/{id}/photo/{photoId}', 'CarController@viewPhoto');
    // загрузка файлов документа для автомобиля
    Route::post('/cars/{id}/uploadDocumentFile/{documentId}', 'CarController@uploadDocumentFiles');
    
    // интерфейс просмотра подразделений
    Route::resource('departments', 'DepartmentController');
    
    // интерфейс просмотра пользователей
    Route::resource('iflatUsers', 'IflatUserController');
    
    // интерфейс работы со списком документов
    Route::resource('documentTypes', 'DocumentTypeController');
    
    // интерфейс работы с документами
    Route::resource('documents', 'DocumentController');
    // создать новый документ указанного типа для автомобиля
    Route::post('/documents/{id}/createCarDocument/{type}', 'DocumentController@createCarDocument');
    
    // загруженные файлы
    // просмотр в браузере
    //Route::get('/media/{id}/view', 'MediaController@viewMedia');
    Route::get('/media/{id}/view/{conversion?}', 'MediaController@viewMedia');
    // скачивание файла
    Route::get('/media/{id}/download', 'MediaController@downloadMedia');
    // удаление файла
    Route::delete('/media/{id}/delete', 'MediaController@deleteMedia');
    
    // типы оповещений
    Route::resource('carNotificationTypes', 'CarNotificationTypeController');
});

// просмотр логов (только для разработки и тестирования)
// @see https://github.com/rap2hpoutre/laravel-log-viewer
Route::get('/systemLogs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->middleware('auth');

app/Http/Controllers/DocumentTypeController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\DocumentTypeDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateDocumentTypeRequest;
use App\Http\Requests\UpdateDocumentTypeRequest;
use App\Repositories\DocumentTypeRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class DocumentTypeController extends AppBaseController
{
    /** 
     * @var  DocumentTypeRepository 
     */
    private $documentTypeRepository;

    public function __construct(DocumentTypeRepository $documentTypeRepo)
    {
        $this->documentTypeRepository = $documentTypeRepo;
    }

    /**
     * Display a listing of the DocumentType.
     *
     * @param DocumentTypeDataTable $documentTypeDataTable
     * @return Response
     */
    public function index(DocumentTypeDataTable $documentTypeDataTable)
    {
        return $documentTypeDataTable->render('document_types.index');
    }

    /**
     * Show the form for creating a new DocumentType.
     *
     * @return Response
     */
    public function create()
    {
        return view('document_types.create');
    }

    /**
     * Store a newly created DocumentType in storage.
     *
     * @param CreateDocumentTypeRequest $request
     *
     * @return Response
     */
    public function store(CreateDocumentTypeRequest $request)
    {
        $input = $request->all();

        $documentType = $this->documentTypeRepository->create($input);

        Flash::success('Создан новый тип документа.');

        return redirect(route('documentTypes.index'));
    }

    /**
     * Display the specified DocumentType.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $documentType = $this->documentTypeRepository->findWithoutFail($id);

        if (empty($documentType)) {
            Flash::error('Document Type not found');

            return redirect(route('documentTypes.index'));
        }

        return view('document_types.show')->with('documentType', $documentType);
    }

    /**
     * Show the form for editing the specified DocumentType.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $documentType = $this->documentTypeRepository->findWithoutFail($id);

        if (empty($documentType)) {
            Flash::error('Document Type not found');

            return redirect(route('documentTypes.index'));
        }

        return view('document_types.edit')->with('documentType', $documentType);
    }

    /**
     * Update the specified DocumentType in storage.
     *
     * @param  int              $id
     * @param UpdateDocumentTypeRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateDocumentTypeRequest $request)
    {
        $documentType = $this->documentTypeRepository->findWithoutFail($id);

        if (empty($documentType)) {
            Flash::error('Document Type not found');

            return redirect(route('documentTypes.index'));
        }

        $documentType = $this->documentTypeRepository->update($request->all(), $id);

        Flash::success('Тип документа обновлен.');

        return redirect(route('documentTypes.index'));
    }

    /**
     * Remove the specified DocumentType from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $documentType = $this->documentTypeRepository->findWithoutFail($id);

        if (empty($documentType)) {
            Flash::error('Document Type not found');

            return redirect(route('documentTypes.index'));
        }

        $this->documentTypeRepository->delete($id);

        Flash::success('Тип документа удален.');

        return redirect(route('documentTypes.index'));
    }
}

resources/views/document_types/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Новый тип документа
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'documentTypes.store']) !!}

                        @include('document_types.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/document_types/datatables_actions.blade.php
{!! Form::open(['route' => ['documentTypes.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('documentTypes.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('documentTypes.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    @if(\App\Models\DocumentType::findOrFail($id)->canBeDeleted())
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type'    => 'submit',
        'class'   => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Удалить этот тип документа?')"
    ])
    !!}
    @endif
</div>
{!! Form::close() !!}

resources/views/document_types/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            {!! $documentType->name !!}
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       @include('flash::message')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($documentType, ['route' => ['documentTypes.update', $documentType->id], 'method' => 'patch']) !!}

                        @include('document_types.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/document_types/fields.blade.php
<?php
/** @var \App\Models\DocumentType $documentType */
// запрещаем изменять код типа документа если для него создан хотя бы один документ
$disableSlug = true;
if (empty($documentType) || $documentType->canBeDeleted()) {
    $disableSlug = false;
}
?>
{!! Form::hidden('id', empty($documentType) ? 0 : $documentType->id) !!}
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Название:') !!}
    {!! Form::text('name', null, ['class' => 'form-control', 'required' => true]) !!}
</div>

<!-- Slug Field -->
<div class="form-group col-sm-6">
    {!! Form::label('slug', 'Код:') !!}
    {!!
        Form::text('slug', null, [
            'class'    => 'form-control',
            'disabled' => $disableSlug,
            'pattern'  => '[A-Za-z0-9_]+',
        ])
    !!}
    Используется для генерации стандартных имен файлов, прикрепляемых к документам этого типа.<br>
    Формат: только латинские буквы, цифры, и знак подчеркивания, без пробелов.<br>
    При создании это поле можно оставить пустым, тогда оно будет заполнено автоматически.<br>
    Это поле нельзя редактировать если был создан хотя бы 1 документ этого типа.<br>
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', 'Описание:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

<!-- TODO Вышестоящий тип документа (для иерархии) -->
<!--div class="form-group col-sm-6">
    {-- Form::label('parent_id', 'Вышестоящий тип:') --}
    {-- Form::number('parent_id', null, ['class' => 'form-control']) --}
</div-->


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Сохранить', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('documentTypes.index') !!}" class="btn btn-default">Отмена</a>
</div>

resources/views/document_types/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Типы документов</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" 
               href="{!! route('documentTypes.create') !!}">Добавить</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('document_types.table')
            </div>
        </div>
    </div>
@endsection

resources/views/document_types/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            {!! $documentType->name !!}
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            @include('flash::message')
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('document_types.show_fields')
                    <a href="{!! route('documentTypes.index') !!}" class="btn btn-default">К списку</a>
                    <a href="/documentTypes/{{ $documentType->id }}/edit" class="btn btn-warning">Редактировать</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/document_types/show_fields.blade.php
<!-- Id Field -->
<!--div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $documentType->id !!}</p>
</div-->

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Название:') !!}
    <p>{!! $documentType->name !!}</p>
</div>

<!-- Slug Field -->
<div class="form-group">
    {!! Form::label('slug', 'Код:') !!}
    <p>{!! $documentType->slug !!}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Описание:') !!}
    <p>{!! $documentType->description !!}</p>
</div>

<!-- Parent Id Field -->
<!--div class="form-group">
    {!! Form::label('parent_id', 'Вышестоящий тип:') !!}
    <p>{!! $documentType->parent_id !!}</p>
</div-->

<!-- Creator Id Field -->
<!--div class="form-group">
    {!! Form::label('creator_id', 'Создан пользователем:') !!}
    <p>{!! $documentType->creator ? $documentType->creator->name : '' !!}</p>
</div-->

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Дата создания:') !!}
    <p>{!! $documentType->created_at->format('Y-m-d H:i:s') !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Последнее изменение:') !!}
    <p>{!! $documentType->updated_at->format('Y-m-d H:i:s') !!}</p>
</div>

<div class="form-group">
    {!! Form::label('cars', 'Все документы этого типа:') !!}
    @if(count($documentType->documents))
        <ul>
            @foreach($documentType->documents as $document)
                <li>
                    <a href="/documents/{{$document->id}}">
                        [{{$document->id}}]:{{ $document->name }}
                    </a>
                    для
                    <a href="/cars/{{$document->car->id}}">
                        {{ $document->car->vendor }} {{ $document->car->model }}
                    </a>
                    [{{ $document->car->reg_number }}]
                </li>
            @endforeach
        </ul>
    @else
        <p>[Нет]</p>
    @endif
</div>

resources/views/document_types/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection