routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect('/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => 'auth'], function($router) {
    // интерфейс управления автомобилями
    Route::resource('cars', 'CarController');
    // загрузка фото для автомобиля
    Route::post('/cars/{id}/uploadPhoto', 'CarController@uploadPhotos');
    // просмотр фото автомобиля
    Route::post('/cars/{id}/photo/{photoId}', 'CarController@viewPhoto');
    // загрузка файлов документа для автомобиля
    Route::post('/cars/{id}/uploadDocumentFile/{documentId}', 'CarController@uploadDocumentFiles');
    
    // интерфейс просмотра подразделений
    Route::resource('departments', 'DepartmentController');
    
    // интерфейс просмотра пользователей
    Route::resource('iflatUsers', 'IflatUserController');
    
    // интерфейс работы со списком документов
    Route::resource('documentTypes', 'DocumentTypeController');
    
    // интерфейс работы с документами
    Route::resource('documents', 'DocumentController');
    // создать новый документ указанного типа для автомобиля
    Route::post('/documents/{id}/createCarDocument/{type}', 'DocumentController@createCarDocument');
    
    // загруженные файлы
    // просмотр в браузере
    //Route::get('/media/{id}/view', 'MediaController@viewMedia');
    Route::get('/media/{id}/view/{conversion?}', 'MediaController@viewMedia');
    // скачивание файла
    Route::get('/media/{id}/download', 'MediaController@downloadMedia');
    // удаление файла
    Route::delete('/media/{id}/delete', 'MediaController@deleteMedia');
    
    // типы оповещений
    Route::resource('carNotificationTypes', 'CarNotificationTypeController');
});

// просмотр логов (только для разработки и тестирования)
// @see https://github.com/rap2hpoutre/laravel-log-viewer
Route::get('/systemLogs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->middleware('auth');

app/Models/IflatUser.php
<?php

namespace App\Models;

// эти классы не используются в коде, но подключены для того чтобы сократить блок комментариев модели
// пожалуйста не убирайте их, чтобы подсказака для IDE продолжала нормально работать
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Notifications\DatabaseNotification;
use Illuminate\Notifications\DatabaseNotificationCollection;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;

// base model class
use Illuminate\Database\Eloquent\Model;
// Eloquence
use Sofa\Eloquence\Eloquence;
use Sofa\Eloquence\Mappable;
use Sofa\Eloquence\Metable;
use Sofa\Eloquence\Mutable;
use Sofa\Eloquence\Validable;
use Sofa\Eloquence\Contracts\CleansAttributes;
use Sofa\Eloquence\Contracts\Validable as ValidableContract;
// Model revisions
use Venturecraft\Revisionable\RevisionableTrait;
// soft deleting
use Illuminate\Database\Eloquent\SoftDeletes;
// model notifications
use Illuminate\Notifications\Notifiable;

/**
 * Сотрудник iflat
 *
 * @SWG\Definition (
 *      definition="IflatUser",
 *      required={"firstname", "lastname"},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="department_id",
 *          description="department_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="firstname",
 *          description="firstname",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="lastname",
 *          description="lastname",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="middlename",
 *          description="middlename",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="email",
 *          description="email",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="phone",
 *          description="phone",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="description",
 *          description="description",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="position",
 *          description="position",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="status",
 *          description="status",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 * @property int                         $id
 * @property int                         $department_id
 * @property string                      $firstname
 * @property string                      $lastname
 * @property string                      $middlename
 * @property string                      $email
 * @property string                      $phone
 * @property string                      $description
 * @property string                      $position
 * @property string                      $status
 * @property \Carbon\Carbon              $created_at
 * @property \Carbon\Carbon              $updated_at
 * @property \Carbon\Carbon              $deleted_at
 * @property-read Collection|Car[]       $cars
 * @property-read \App\Models\Department $department
 * @method static \Illuminate\Database\Query\Builder|\App\Models\IflatUser whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\IflatUser whereDeletedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\IflatUser whereDepartmentId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\IflatUser whereDescription($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\IflatUser whereEmail($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\IflatUser whereFirstname($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\IflatUser whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\IflatUser whereLastname($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\IflatUser whereMiddlename($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\IflatUser wherePhone($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\IflatUser wherePosition($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\IflatUser whereStatus($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\IflatUser whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property string $full_name
 * @property-read string|null $mapping_for
 * @property-read \Sofa\Eloquence\Metable\AttributeBag $meta_attributes
 * @property-read \Illuminate\Database\Eloquent\Collection|\Sofa\Eloquence\Metable\Attribute[] $metaAttributes
 * @property-read \Illuminate\Database\Eloquent\Collection|\Venturecraft\Revisionable\Revision[] $revisionHistory
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 */
class IflatUser extends Model implements ValidableContract, CleansAttributes
{
    /**
     * @see https://github.com/jarektkaczyk/eloquence/wiki/Base
     */
    use Eloquence, Mappable, Metable, Mutable, Validable;
    /**
     * @see https://laravel.com/docs/5.3/eloquent#soft-deleting
     */
    use SoftDeletes;
    /**
     * @see https://github.com/VentureCraft/revisionable
     */
    use RevisionableTrait;
    /**
     * @see https://laravel.com/docs/5.3/notifications#sending-notifications
     */
    use Notifiable;
    
    /**
     * @var string
     */
    public $table = 'iflat_users';
    
    /**
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];
    /**
     * @var array
     */
    public $fillable = [
        'department_id',
        'firstname',
        'lastname',
        'middlename',
        'email',
        'phone',
        'description',
        'position',
        'status',
    ];
    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id'            => 'integer',
        'department_id' => 'integer',
        'firstname'     => 'string',
        'lastname'      => 'string',
        'middlename'    => 'string',
        'email'         => 'string',
        'phone'         => 'string',
        'description'   => 'string',
        'position'      => 'string',
        'status'        => 'string',
    ];
    /**
     * @var bool - записывать операцию создания записи в историю изменений объекта
     *
     * @see https://github.com/VentureCraft/revisionable#storing-creations
     */
    protected $revisionCreationsEnabled = true;
    /**
     * @var array - список полей, исключенных из истории изменений
     *
     * @see https://github.com/VentureCraft/revisionable#more-control
     */
    protected $dontKeepRevisionOf = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];
    
    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'firstname' => 'required',
        'lastname'  => 'required',
    ];
    
    /**
     * Route notifications for the Slack channel.
     *
     * @return string
     */
    public function routeNotificationForSlack()
    {
        return config('services.slack.webhook_url');
    }
    
    /// RELATIONS ///
    
    /**
     * Все автомобили закрепленные за сотрудником
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany|Car[]
     */
    public function cars()
    {
        return $this->hasMany(Car::class);
    }
    
    /**
     * Подразделение в котором числится сотрудник
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo|Department
     */
    public function department()
    {
        return $this->belongsTo(Department::class);
    }
    
    /// GETTERS & SETTERS ///
    
    /**
     *
     * @return string
     */
    public function getFullNameAttribute()
    {
        return $this->lastname . ' ' . $this->firstname . ' ' . $this->middlename;
    }
    
    /**
     *
     * @param string
     * 
     * @return null
     */
    public function setFullNameAttribute($fullName)
    {
        $nameData = explode(' ', $fullName);
        if (isset($nameData[0])) {
            $this->lastname = $nameData[0];
        }
        if (isset($nameData[1])) {
            $this->firstname = $nameData[1];
        }
        if (isset($nameData[2])) {
            $this->middlename = $nameData[2];
        }
    }
}

app/Http/Controllers/IflatUserController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\IflatUserDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateIflatUserRequest;
use App\Http\Requests\UpdateIflatUserRequest;
use App\Repositories\IflatUserRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class IflatUserController extends AppBaseController
{
    /** 
     * @var  IflatUserRepository 
     */
    private $iflatUserRepository;

    public function __construct(IflatUserRepository $iflatUserRepo)
    {
        $this->iflatUserRepository = $iflatUserRepo;
    }

    /**
     * Display a listing of the IflatUser.
     *
     * @param IflatUserDataTable $iflatUserDataTable
     * @return Response
     */
    public function index(IflatUserDataTable $iflatUserDataTable)
    {
        return $iflatUserDataTable->render('iflat_users.index');
    }

    /**
     * Show the form for creating a new IflatUser.
     *
     * @return Response
     */
    public function create()
    {
        return view('iflat_users.create');
    }

    /**
     * Store a newly created IflatUser in storage.
     *
     * @param CreateIflatUserRequest $request
     *
     * @return Response
     */
    public function store(CreateIflatUserRequest $request)
    {
        $input = $request->all();

        $iflatUser = $this->iflatUserRepository->create($input);

        Flash::success('Iflat User saved successfully.');

        return redirect(route('iflatUsers.index'));
    }

    /**
     * Display the specified IflatUser.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $iflatUser = $this->iflatUserRepository->findWithoutFail($id);

        if (empty($iflatUser)) {
            Flash::error('Iflat User not found');

            return redirect(route('iflatUsers.index'));
        }

        return view('iflat_users.show')->with('iflatUser', $iflatUser);
    }

    /**
     * Show the form for editing the specified IflatUser.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $iflatUser = $this->iflatUserRepository->findWithoutFail($id);

        if (empty($iflatUser)) {
            Flash::error('Iflat User not found');

            return redirect(route('iflatUsers.index'));
        }

        return view('iflat_users.edit')->with('iflatUser', $iflatUser);
    }

    /**
     * Update the specified IflatUser in storage.
     *
     * @param  int              $id
     * @param UpdateIflatUserRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateIflatUserRequest $request)
    {
        $iflatUser = $this->iflatUserRepository->findWithoutFail($id);

        if (empty($iflatUser)) {
            Flash::error('Iflat User not found');

            return redirect(route('iflatUsers.index'));
        }

        $iflatUser = $this->iflatUserRepository->update($request->all(), $id);

        Flash::success('Iflat User updated successfully.');

        return redirect(route('iflatUsers.index'));
    }

    /**
     * Remove the specified IflatUser from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $iflatUser = $this->iflatUserRepository->findWithoutFail($id);

        if (empty($iflatUser)) {
            Flash::error('Iflat User not found');

            return redirect(route('iflatUsers.index'));
        }

        $this->iflatUserRepository->delete($id);

        Flash::success('Iflat User deleted successfully.');

        return redirect(route('iflatUsers.index'));
    }
}

resources/views/iflat_users/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Новая запись
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'iflatUsers.store']) !!}

                        @include('iflat_users.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/iflat_users/datatables_actions.blade.php
<div class='btn-group'>
    <a href="{{ route('iflatUsers.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
</div>

resources/views/iflat_users/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            {!! $iflatUser->name !!}
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($iflatUser, ['route' => ['iflatUsers.update', $iflatUser->id], 'method' => 'patch']) !!}

                        @include('iflat_users.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/iflat_users/fields.blade.php
<!-- Department Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('department_id', 'Department Id:') !!}
    {!! Form::number('department_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Firstname Field -->
<div class="form-group col-sm-6">
    {!! Form::label('firstname', 'Firstname:') !!}
    {!! Form::text('firstname', null, ['class' => 'form-control']) !!}
</div>

<!-- Lastname Field -->
<div class="form-group col-sm-6">
    {!! Form::label('lastname', 'Lastname:') !!}
    {!! Form::text('lastname', null, ['class' => 'form-control']) !!}
</div>

<!-- Middlename Field -->
<div class="form-group col-sm-6">
    {!! Form::label('middlename', 'Middlename:') !!}
    {!! Form::text('middlename', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::text('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Phone:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Position Field -->
<div class="form-group col-sm-6">
    {!! Form::label('position', 'Position:') !!}
    {!! Form::text('position', null, ['class' => 'form-control']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::text('status', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Сохранить', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('iflatUsers.index') !!}" class="btn btn-default">Отмена</a>
</div>

resources/views/iflat_users/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Сотрудники</h1>
        <h1 class="pull-right">
           <!--a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" 
               href="{!! route('iflatUsers.create') !!}">Добавить</a-->
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('iflat_users.table')
            </div>
        </div>
    </div>
@endsection

resources/views/iflat_users/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            {!! $iflatUser->fullName !!}
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('iflat_users.show_fields')
                    <a href="{!! route('iflatUsers.index') !!}" class="btn btn-default">Назад</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/iflat_users/show_fields.blade.php
<!-- Id Field -->
<!--div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $iflatUser->id !!}</p>
</div-->

<!-- Department Id Field -->
<!--div class="form-group">
    {!! Form::label('department_id', 'Department Id:') !!}
    <p>{!! $iflatUser->department_id !!}</p>
</div-->

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $iflatUser->email !!}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', 'Телефон:') !!}
    <p>{!! $iflatUser->phone !!}</p>
</div>

<!-- Description Field -->
@if($iflatUser->description)
<div class="form-group">
    {!! Form::label('description', 'Описание:') !!}
    <p>{!! $iflatUser->description !!}</p>
</div>
@endif

<!-- Position Field -->
<div class="form-group">
    {!! Form::label('position', 'Должность:') !!}
    <p>{!! $iflatUser->position !!}</p>
</div>

<div class="form-group">
    {!! Form::label('cars', 'Автомобили:') !!}
    @if(count($iflatUser->cars))
        <ul>
        @foreach($iflatUser->cars as $car)
            <li>
                <a href="/cars/{{$car->id}}">{{ $car->vendor }} {{ $car->model }}</a>
                {{ $car->reg_number }}
            </li>
        @endforeach
        </ul>
    @else
        <p>[Нет]</p>
    @endif
</div>

<!-- Status Field -->
<!--div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    <p>{!! $iflatUser->status !!}</p>
</div-->

resources/views/iflat_users/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection