routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect('/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => 'auth'], function($router) {
    // интерфейс управления автомобилями
    Route::resource('cars', 'CarController');
    // загрузка фото для автомобиля
    Route::post('/cars/{id}/uploadPhoto', 'CarController@uploadPhotos');
    // просмотр фото автомобиля
    Route::post('/cars/{id}/photo/{photoId}', 'CarController@viewPhoto');
    // загрузка файлов документа для автомобиля
    Route::post('/cars/{id}/uploadDocumentFile/{documentId}', 'CarController@uploadDocumentFiles');
    
    // интерфейс просмотра подразделений
    Route::resource('departments', 'DepartmentController');
    
    // интерфейс просмотра пользователей
    Route::resource('iflatUsers', 'IflatUserController');
    
    // интерфейс работы со списком документов
    Route::resource('documentTypes', 'DocumentTypeController');
    
    // интерфейс работы с документами
    Route::resource('documents', 'DocumentController');
    // создать новый документ указанного типа для автомобиля
    Route::post('/documents/{id}/createCarDocument/{type}', 'DocumentController@createCarDocument');
    
    // загруженные файлы
    // просмотр в браузере
    //Route::get('/media/{id}/view', 'MediaController@viewMedia');
    Route::get('/media/{id}/view/{conversion?}', 'MediaController@viewMedia');
    // скачивание файла
    Route::get('/media/{id}/download', 'MediaController@downloadMedia');
    // удаление файла
    Route::delete('/media/{id}/delete', 'MediaController@deleteMedia');
    
    // типы оповещений
    Route::resource('carNotificationTypes', 'CarNotificationTypeController');
});

// просмотр логов (только для разработки и тестирования)
// @see https://github.com/rap2hpoutre/laravel-log-viewer
Route::get('/systemLogs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->middleware('auth');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>iFlat Автотранспорт</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.11/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.11/css/skins/_all-skins.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">
    
    <!-- laradrop -->
    <!--link href="/vendor/jasekz/laradrop/css/styles.css" rel="stylesheet" type="text/css"-->

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- blueimp Gallery styles -->
    <link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
    <!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
    <link rel="stylesheet" href="/vendor/jquery-file-upload/css/jquery.fileupload.css">
    <link rel="stylesheet" href="/vendor/jquery-file-upload/css/jquery.fileupload-ui.css">

    <!-- photoswipe -->
    <!-- Core photoswipe CSS file -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.2/photoswipe.min.css" integrity="sha256-rlldBDOCxqXAE1fRopHG2SqpgWisq17/3Oleo+1CBKo=" crossorigin="anonymous" />
    <!-- Skin photoswipe CSS file (styling of UI - buttons, caption, etc.)
         In the folder of skin CSS file there are also:
         - .png and .svg icons sprite, 
         - preloader.gif (for browsers that do not support CSS animations) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.2/default-skin/default-skin.min.css" integrity="sha256-kQW7k22C0skJMSPxgEI2VHR0LPHeygi8SRYNvV/DB2w=" crossorigin="anonymous" />
    <!-- Core photoswipe JS file -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.2/photoswipe.min.js" integrity="sha256-iG1tiE5xJSJQhKdeOW4cPiSy+RTrnRKjjjrVQ0hexug=" crossorigin="anonymous"></script>
    <!-- UI photoswipe JS file -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.2/photoswipe-ui-default.min.js" integrity="sha256-XvSk6Opq7XZ8oUcx213MtikXtbl5bbe4Q9tr4+NJBCg=" crossorigin="anonymous"></script>

    @yield('css')
</head>

<body class="skin-blue sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">

            <!-- Logo -->
            <a href="#" class="logo">
                <b>iFlat</b>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Навигация</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg"
                                     class="user-image" alt="User Image"/>
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">{!! Auth::user()->name !!}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg"
                                         class="img-circle" alt="User Image"/>
                                    <p>
                                        {!! Auth::user()->name !!}
                                        <small>Дата регистрации {!! Auth::user()->created_at->format('M. Y') !!}</small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Профиль</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{!! url('/logout') !!}" class="btn btn-default btn-flat"
                                            onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            Выйти
                                        </a>
                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        @include('layouts.sidebar')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @yield('content')
        </div>

        <!-- Main Footer -->
        <footer class="main-footer" style="max-height: 100px;text-align: center">
            <strong><a href="#">iFlat</a> - управление автотранспортом</strong>
        </footer>

    </div>
@else
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Навигация</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{!! url('/') !!}">
                    iFlat - Автотранспорт
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{!! url('/home') !!}">Главная</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    <li><a href="{!! url('/login') !!}">Вход</a></li>
                    <li><a href="{!! url('/register') !!}">Регистрация</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
    @endif

    <!-- jQuery 3.1.1 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>

    <!-- AdminLTE App -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.11/js/app.min.js"></script>

    @if (!Auth::guest())
    <!-- Laravel File Manager -->
    <script src="/vendor/laravel-filemanager/js/lfm.js"></script>
    
    <!-- jQuery file upload -->
    <script src="/vendor/jquery-file-upload/js/vendor/jquery.ui.widget.js"></script>
    <!-- The Load Image plugin is included for the preview images and image resizing functionality -->
    <script src="//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
    <!-- The Canvas to Blob plugin is included for image resizing functionality -->
    <script src="//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
    <script src="/vendor/jquery-file-upload/js/jquery.iframe-transport.js"></script>
    <script src="/vendor/jquery-file-upload/js/jquery.fileupload.js"></script>
    <script src="/vendor/jquery-file-upload/js/jquery.fileupload-process.js"></script>
    <script src="/vendor/jquery-file-upload/js/jquery.fileupload-image.js"></script>
    <script src="/vendor/jquery-file-upload/js/jquery.fileupload-ui.js"></script>
    <script src="/vendor/jquery-file-upload/js/jquery.fileupload-validate.js"></script>
    @endif

    @if (!Auth::guest())
    <script>
        /**
         * Удалить выбранный файл
         *
         * @param id
         */
        function deleteMedia(id) {
            deleteConfirmed = confirm('Вы уверены что хотите удалить этот файл?');
            if (deleteConfirmed) {
                $.ajax({
                    url: '/media/' + id + '/delete',
                    type: 'DELETE',
                    data: {
                        '_token' : '{{csrf_token()}}'
                    },
                    headers : {
                        'x-csrf-token' : '{{csrf_token()}}'
                    },
                    success: function(result) {
                        $('#media_list_item_' + id).fadeOut(400).remove();
                    }
                });
            }
        }
    </script>
    @endif
    
    @yield('scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menu.blade.php
<li class="{{ Request::is('cars*') ? 'active' : '' }}">
    <a href="{!! route('cars.index') !!}"><i class="fa fa-car"></i><span>Автомобили</span></a>
</li>

<li class="{{ Request::is('departments*') ? 'active' : '' }}">
    <a href="{!! route('departments.index') !!}"><i class="fa fa-building"></i><span>Подразделения</span></a>
</li>

<li class="{{ Request::is('iflatUsers*') ? 'active' : '' }}">
    <a href="{!! route('iflatUsers.index') !!}"><i class="fa fa-user"></i><span>Сотрудники</span></a>
</li>

<li class="{{ Request::is('documents*') ? 'active' : '' }}">
    <a href="{!! route('documents.index') !!}"><i class="fa fa-files-o"></i><span>Документы</span></a>
</li>

<li>
    <span><b style="color: #fff;padding-left: 20px;">Администрирование</b></span>
</li>

<li class="{{ Request::is('documentTypes*') ? 'active' : '' }}">
    <a href="{!! route('documentTypes.index') !!}"><i class="fa fa-file-text"></i><span>Типы документов</span></a>
</li>

<li class="{{ Request::is('carNotificationTypes*') ? 'active' : '' }}">
    <a href="{!! route('carNotificationTypes.index') !!}"><i class="fa fa-bell"></i><span>Типы оповещений</span></a>
</li>

<li class="{{ Request::is('systemLogs*') ? 'active' : '' }}">
    <a href="/systemLogs" target="_blank"><i class="fa fa-terminal"></i><span>Журнал событий</span></a>
</li>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg" class="img-circle"
                     alt="User Image"/>
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>iFlat</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> В сети</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <!--form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Поиск..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form-->
        <!-- Sidebar Menu -->

        <ul class="sidebar-menu">
            @include('layouts.menu')
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>