routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect('/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => 'auth'], function($router) {
    // интерфейс управления автомобилями
    Route::resource('cars', 'CarController');
    // загрузка фото для автомобиля
    Route::post('/cars/{id}/uploadPhoto', 'CarController@uploadPhotos');
    // просмотр фото автомобиля
    Route::post('/cars/{id}/photo/{photoId}', 'CarController@viewPhoto');
    // загрузка файлов документа для автомобиля
    Route::post('/cars/{id}/uploadDocumentFile/{documentId}', 'CarController@uploadDocumentFiles');
    
    // интерфейс просмотра подразделений
    Route::resource('departments', 'DepartmentController');
    
    // интерфейс просмотра пользователей
    Route::resource('iflatUsers', 'IflatUserController');
    
    // интерфейс работы со списком документов
    Route::resource('documentTypes', 'DocumentTypeController');
    
    // интерфейс работы с документами
    Route::resource('documents', 'DocumentController');
    // создать новый документ указанного типа для автомобиля
    Route::post('/documents/{id}/createCarDocument/{type}', 'DocumentController@createCarDocument');
    
    // загруженные файлы
    // просмотр в браузере
    //Route::get('/media/{id}/view', 'MediaController@viewMedia');
    Route::get('/media/{id}/view/{conversion?}', 'MediaController@viewMedia');
    // скачивание файла
    Route::get('/media/{id}/download', 'MediaController@downloadMedia');
    // удаление файла
    Route::delete('/media/{id}/delete', 'MediaController@deleteMedia');
    
    // типы оповещений
    Route::resource('carNotificationTypes', 'CarNotificationTypeController');
});

// просмотр логов (только для разработки и тестирования)
// @see https://github.com/rap2hpoutre/laravel-log-viewer
Route::get('/systemLogs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->middleware('auth');

app/Http/Controllers/CarNotificationTypeController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\CarNotificationTypeDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateCarNotificationTypeRequest;
use App\Http\Requests\UpdateCarNotificationTypeRequest;
use App\Repositories\CarNotificationTypeRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class CarNotificationTypeController extends AppBaseController
{
    /** 
     * @var  CarNotificationTypeRepository 
     */
    private $carNotificationTypeRepository;

    public function __construct(CarNotificationTypeRepository $carNotificationTypeRepo)
    {
        $this->carNotificationTypeRepository = $carNotificationTypeRepo;
    }

    /**
     * Display a listing of the CarNotificationType.
     *
     * @param CarNotificationTypeDataTable $carNotificationTypeDataTable
     * @return Response
     */
    public function index(CarNotificationTypeDataTable $carNotificationTypeDataTable)
    {
        return $carNotificationTypeDataTable->render('car_notification_types.index');
    }

    /**
     * Show the form for creating a new CarNotificationType.
     *
     * @return Response
     */
    public function create()
    {
        return view('car_notification_types.create');
    }

    /**
     * Store a newly created CarNotificationType in storage.
     *
     * @param CreateCarNotificationTypeRequest $request
     *
     * @return Response
     */
    public function store(CreateCarNotificationTypeRequest $request)
    {
        $input = $request->all();

        $carNotificationType = $this->carNotificationTypeRepository->create($input);

        Flash::success('Тип оповещения создан.');

        return redirect(route('carNotificationTypes.index'));
    }

    /**
     * Display the specified CarNotificationType.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $carNotificationType = $this->carNotificationTypeRepository->findWithoutFail($id);

        if (empty($carNotificationType)) {
            Flash::error('Car Notification Type not found');

            return redirect(route('carNotificationTypes.index'));
        }

        return view('car_notification_types.show')->with('carNotificationType', $carNotificationType);
    }

    /**
     * Show the form for editing the specified CarNotificationType.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $carNotificationType = $this->carNotificationTypeRepository->findWithoutFail($id);

        if (empty($carNotificationType)) {
            Flash::error('Car Notification Type not found');

            return redirect(route('carNotificationTypes.index'));
        }

        return view('car_notification_types.edit')->with('carNotificationType', $carNotificationType);
    }

    /**
     * Update the specified CarNotificationType in storage.
     *
     * @param  int              $id
     * @param UpdateCarNotificationTypeRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCarNotificationTypeRequest $request)
    {
        $carNotificationType = $this->carNotificationTypeRepository->findWithoutFail($id);

        if (empty($carNotificationType)) {
            Flash::error('Car Notification Type not found');

            return redirect(route('carNotificationTypes.index'));
        }

        $carNotificationType = $this->carNotificationTypeRepository->update($request->all(), $id);

        Flash::success('Оповещение обновлено.');

        return redirect(route('carNotificationTypes.index'));
    }

    /**
     * Remove the specified CarNotificationType from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $carNotificationType = $this->carNotificationTypeRepository->findWithoutFail($id);

        if (empty($carNotificationType)) {
            Flash::error('Car Notification Type not found');

            return redirect(route('carNotificationTypes.index'));
        }

        $this->carNotificationTypeRepository->delete($id);

        Flash::success('Тип оповещения удален.');

        return redirect(route('carNotificationTypes.index'));
    }
}

resources/views/car_notification_types/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Новый тип оповещения
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'carNotificationTypes.store']) !!}

                        @include('car_notification_types.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/car_notification_types/datatables_actions.blade.php
{!! Form::open(['route' => ['carNotificationTypes.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('carNotificationTypes.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('carNotificationTypes.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Вы уверены?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/car_notification_types/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            {!! $carNotificationType->name !!}
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($carNotificationType, ['route' => ['carNotificationTypes.update', $carNotificationType->id], 'method' => 'patch']) !!}

                        @include('car_notification_types.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/car_notification_types/fields.blade.php
<?php
$eventOptions = \App\Models\CarNotificationType::getTriggerEventOptions();
?>
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Название:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('description', 'Описание:') !!}
    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Trigger Event Field -->
<div class="form-group col-sm-6">
    {!! Form::label('trigger_event', 'Событие, запускающее оповещение:') !!}
    {!! Form::select('trigger_event', $eventOptions, null) !!}
</div>

<!-- Subject Template Field -->
<div class="form-group col-sm-6">
    {!! Form::label('subject_template', 'Шаблон темы оповещения:') !!}
    {!! Form::text('subject_template', null, ['class' => 'form-control']) !!}
</div>

<!-- Action Text Template Field -->
<div class="form-group col-sm-6">
    {!! Form::label('action_text_template', 'Шаблон текста на кнопке действия:') !!}
    {!! Form::text('action_text_template', null, ['class' => 'form-control']) !!}
</div>

<!-- Action Url Template Field -->
<div class="form-group col-sm-6">
    {!! Form::label('action_url_template', 'Шаблон Url для действия:') !!}
    {!! Form::text('action_url_template', null, ['class' => 'form-control']) !!}
</div>

<!-- Email Template Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('email_template', 'Email-Шаблон:') !!}
    {!! Form::textarea('email_template', null, ['class' => 'form-control']) !!}
</div>

<!-- Sms Template Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('sms_template', 'Sms-Шаблон:') !!}
    {!! Form::textarea('sms_template', null, ['class' => 'form-control']) !!}
</div>

<!-- Slack Template Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('slack_template', 'Slack-Шаблон:') !!}
    {!! Form::textarea('slack_template', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Сохранить', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('carNotificationTypes.index') !!}" class="btn btn-default">Отмена</a>
</div>

resources/views/car_notification_types/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Типы оповещений</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" 
               href="{!! route('carNotificationTypes.create') !!}">Добавить</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('car_notification_types.table')
            </div>
        </div>
    </div>
@endsection

resources/views/car_notification_types/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            {!! $carNotificationType->name !!}
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('car_notification_types.show_fields')
                    <a href="{!! route('carNotificationTypes.index') !!}" class="btn btn-default">Назад</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/car_notification_types/show_fields.blade.php
<?php
$eventOptions = \App\Models\CarNotificationType::getTriggerEventOptions();
?>
<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Описание:') !!}
    <p>{!! $carNotificationType->description !!}</p>
</div>

<!-- Trigger Event Field -->
<div class="form-group">
    {!! Form::label('trigger_event', 'Событие, запускающее оповещение:') !!}
    <p>{!! $eventOptions[$carNotificationType->trigger_event] !!} [{!! $carNotificationType->trigger_event !!}]</p>
</div>

<!-- Subject Template Field -->
<div class="form-group">
    {!! Form::label('subject_template', 'Шаблон темы оповещения:') !!}
    <p>{!! $carNotificationType->subject_template !!}</p>
</div>

<!-- Action Text Template Field -->
<div class="form-group">
    {!! Form::label('action_text_template', 'Шаблон текста на кнопке действия:') !!}
    <p>{!! $carNotificationType->action_text_template !!}</p>
</div>

<!-- Action Url Template Field -->
<div class="form-group">
    {!! Form::label('action_url_template', 'Шаблон Url для действия:') !!}
    <p>{!! $carNotificationType->action_url_template !!}</p>
</div>

<!-- Email Template Field -->
<div class="form-group">
    {!! Form::label('email_template', 'Email-Шаблон:') !!}
    <p>{!! $carNotificationType->email_template !!}</p>
</div>

<!-- Sms Template Field -->
<div class="form-group">
    {!! Form::label('sms_template', 'Sms-Шаблон:') !!}
    <p>{!! $carNotificationType->sms_template !!}</p>
</div>

<!-- Slack Template Field -->
<div class="form-group">
    {!! Form::label('slack_template', 'Slack-Шаблон:') !!}
    <p>{!! $carNotificationType->slack_template !!}</p>
</div>

resources/views/car_notification_types/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection